name: Docker Build and Push

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare image name
        id: prep
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')"
          echo "REGISTRY_IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Timestamp
        id: ts
        run: echo "ts=$(date -u +%Y%m%d-%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=prod-${{ steps.ts.outputs.ts }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summary
        run: |
          echo "# Docker Image Published" >> "$GITHUB_STEP_SUMMARY"
          echo "Image: ${{ steps.prep.outputs.image }}" >> "$GITHUB_STEP_SUMMARY"
          echo "## Tags" >> "$GITHUB_STEP_SUMMARY"
          echo "${{ steps.meta.outputs.tags }}" | sed 's/^/- /' >> "$GITHUB_STEP_SUMMARY"
