name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        id: eslint
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier check
        id: prettier
        run: npm run format:check
        continue-on-error: true

      - name: Summarize and annotate
        if: always()
        run: |
          has_error=0
          if [ "${{ steps.eslint.outcome }}" != "success" ]; then
            echo "::error title=ESLint failed::Run 'npm run lint:fix' to automatically fix issues where possible." 
            has_error=1
          fi
          if [ "${{ steps.prettier.outcome }}" != "success" ]; then
            echo "::error title=Prettier check failed::Run 'npm run format' to format the codebase." 
            has_error=1
          fi

          {
            echo "# Lint & Format Results"
            echo
            echo "- ESLint: ${{ steps.eslint.outcome }}"
            echo "- Prettier: ${{ steps.prettier.outcome }}"
            echo
            echo "If failed, try:"
            echo "- npm run lint:fix"
            echo "- npm run format"
          } >> "$GITHUB_STEP_SUMMARY"

          if [ "$has_error" -ne 0 ]; then
            exit 1
          fi
