name: Tests

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      NODE_OPTIONS: --experimental-vm-modules
      DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        id: tests
        run: npm test
        continue-on-error: true

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.sha }}
          path: |
            coverage/**
          if-no-files-found: ignore
          retention-days: 30

      - name: Test summary and annotations
        if: always()
        run: |
          if [ "${{ steps.tests.outcome }}" = "success" ]; then
            echo "# Test Results" >> "$GITHUB_STEP_SUMMARY"
            echo "All tests passed." >> "$GITHUB_STEP_SUMMARY"
          else
            echo "::error title=Tests failed::Check the logs above for failure details."
            echo "# Test Results" >> "$GITHUB_STEP_SUMMARY"
            echo "Tests failed. See logs for details." >> "$GITHUB_STEP_SUMMARY"
            exit 1
          fi
